### ISSUE TITLE
Silk Touch on Shears

### ISSUE THREAD

**Issue by blacksythe** [benbenlaw/skyopolis4#20]
Not sure if this is intentional or not, but silk touch appears on both clay and wooden shears, this prevents access to things like shearing vines, Botania flowers and a few other things that cant be silk touched..

I propose removing the enchant from the clay shears to alleviate this issue and keep the wooden shears with silk touch to protect the early game.

This would allow completion of the early game quest book (which seems to be the intention) before moving onto a new page.

**Comment by benbenlaw** [comment]
thres currently a bug with shears so i had to enchant with silk touch to get leaves
