### ISSUE TITLE
sky bucks in thermal

### ISSUE THREAD

**Issue by benbenlaw** [benbenlaw/skyopolis4#32]
What if we could use skybucks in the Thermal Expansion coin generator  ?
NEW

BrotherEarth967Today at 1:17 PM
They'd have to make a lot of power but that's a really good idea

ChJeesToday at 1:18 PM
1 million RF each.

BrotherEarth967Today at 1:18 PM
Spend a skybuck for a quick massive power surge
[1:18 PM]
I like it

**Comment by Sir420Yoshii** [comment]
Soudsn cool Idea, Also added mod i came across mate,

**Comment by benbenlaw** [comment]
this has been added along with dust being used in anyother thermal generator
