### ISSUE TITLE
Problems entering the official 5.1 server 

### ISSUE THREAD

**Issue by ElementaryHeart** [benbenlaw/skyopolis4#38]
It seems to me that the list of mods is not compatible and I am in the latest version, I also see that there are people connected:,

**Comment by LegendarySkar** [comment]
There's been a fix for the end dimension on the server. It was announced on Discord.
You have to manually update the mod The Outer End to version 0.2.8 to join the server. You can find it here: https://www.curseforge.com/minecraft/mc-mods/the-outer-end/files/3195106
Either download it manually, place it in your mods folder and delete the old version, or update the mod in your launcher.

In the CurseForge Launcher you have to open the profile options and allow content management. Then you can add more content, search for outer end and hit the update button.

In GDLauncher you have to right-click, select manage, go to mods, search outer, click on the mod, select version 0.2.8 and hit the switch version button.
