### ISSUE TITLE
The Vending Machine is broken and i can't do anything with it

### ISSUE THREAD

**Issue by Ducc2u490** [benbenlaw/skyopolis4#40]
i cant interact with it whatsoever

**Comment by benbenlaw** [comment]
in what way?

**Comment by Ducc2u490** [comment]
I'm not sure how it is supposed to be used but nothing I tried works

**Comment by benbenlaw** [comment]
place it down
right click show items

**Comment by Ducc2u490** [comment]
when i right click it nothing happens though, I'll restart my game and retry

**Comment by Ducc2u490** [comment]
Alright the restart fixed the vending machine! everything else worked fine so far, im starting to like the modpack

**Comment by benbenlaw** [comment]
haha ok cool, join the discord if you need any more help
