### ISSUE TITLE
Quest More Ingots cant be finished

### ISSUE THREAD

**Issue by thomasoien** [benbenlaw/skyopolis4#5]
It wants the Immersive engineering silver ingot but you can only get thermal one when smelting silver dust

![Untitled](https://user-images.githubusercontent.com/77233339/104125006-61e9c280-5354-11eb-8e09-32c5091ef372.png)

**Comment by benbenlaw** [comment]
Changed the ingots and dust quests to accept items in the same tags, Should be fixed
