### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by magicdiablo** [benbenlaw/skyopolis4#8]
Putting 2 damaged wooden shear in a crafting area will result in a repaired shears.  Cool, but you can infinitely pull out the repaired shears.  Below is the before and after effect.  Currently this only works with the wooden shears.  Vanilla tools still work correctly.
![FML early loading progress 1_25_2021 12_16_21 PM](https://user-images.githubusercontent.com/49598531/105740463-3eec1080-5f07-11eb-9139-1a6af0c44f35.png)
![FML early loading progress 1_25_2021 12_16_30 PM](https://user-images.githubusercontent.com/49598531/105740489-401d3d80-5f07-11eb-98f2-2ee880eb40d7.png)

**Comment by benbenlaw** [comment]
this is a known issue please checl the know bugs in the main menu thanks for reporting

**Comment by magicdiablo** [comment]
Oh, didn't realize that was even there.  Good to know.  I'll pay more attention.

**Comment by benbenlaw** [comment]
i will leave it open till its been fixed incase other people notice it
